// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f7DE9y7qp46fyCw5nuY8f9
// Component: x8mEiwhu6Vco

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import { Button } from "../../Button"; // plasmic-import: NvY5LE-Ew6FA/codeComponent
import { TextInput } from "../../TextInput"; // plasmic-import: vyWUomJMQins/codeComponent
import { Dropdown } from "../../DropDown"; // plasmic-import: nH3JopN08-ry/codeComponent
import { Option } from "../../Option"; // plasmic-import: MjV_affoGMMz/codeComponent
import { JobCard } from "../../jobCard/JobCard"; // plasmic-import: epi6kICoBl8S/codeComponent
import { Map } from "../../Map"; // plasmic-import: 0X49CVAH3as3/codeComponent
import { Footerlink } from "../../Footerlink"; // plasmic-import: AsZg43QQ7RIK/codeComponent
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariantshm8Nko4B5BDd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: HM8Nko4B5BDd/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: f7DE9y7qp46fyCw5nuY8f9/projectcss
import sty from "./PlasmicAccueil.module.css"; // plasmic-import: x8mEiwhu6Vco/css

import Group2Icon from "./icons/PlasmicIcon__Group2"; // plasmic-import: EDrRfJFrGIzr/icon
import Mail2Icon from "./icons/PlasmicIcon__Mail2"; // plasmic-import: rZP3MS1dOHIL/icon
import ZapIcon from "./icons/PlasmicIcon__Zap"; // plasmic-import: c9TD4NnDdoCa/icon
import BarChart2Icon from "./icons/PlasmicIcon__BarChart2"; // plasmic-import: 9Oxczg72Yias/icon
import SocialIcon2Icon from "./icons/PlasmicIcon__SocialIcon2"; // plasmic-import: 85_PHFbzbYbc/icon
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: uW8IxWz2drGt/icon
import Group4Icon from "./icons/PlasmicIcon__Group4"; // plasmic-import: jg2ejGQewG0B/icon

createPlasmicElementProxy;

export type PlasmicAccueil__VariantMembers = {};
export type PlasmicAccueil__VariantsArgs = {};
type VariantPropType = keyof PlasmicAccueil__VariantsArgs;
export const PlasmicAccueil__VariantProps = new Array<VariantPropType>();

export type PlasmicAccueil__ArgsType = {};
type ArgPropType = keyof PlasmicAccueil__ArgsType;
export const PlasmicAccueil__ArgProps = new Array<ArgPropType>();

export type PlasmicAccueil__OverridesType = {
  root?: Flex__<"div">;
  structureLp?: Flex__<"div">;
  nav?: Flex__<"div">;
  frame?: Flex__<"div">;
  frame2?: Flex__<"div">;
  frame3?: Flex__<"div">;
  frame4?: Flex__<"div">;
  frame5?: Flex__<"div">;
  menuItems?: Flex__<"div">;
  frame1437254391?: Flex__<"div">;
  frame15?: Flex__<"div">;
  searchBar?: Flex__<"div">;
  frame12?: Flex__<"div">;
  textInput?: Flex__<typeof TextInput>;
  inputLieu?: Flex__<typeof TextInput>;
  dropdown?: Flex__<typeof Dropdown>;
  dropdown3?: Flex__<typeof Dropdown>;
  frame14?: Flex__<"div">;
  frame13?: Flex__<"div">;
  dropdown4?: Flex__<typeof Dropdown>;
  dropdown5?: Flex__<typeof Dropdown>;
  dropdown8?: Flex__<typeof Dropdown>;
  dropdown9?: Flex__<typeof Dropdown>;
  dropdown6?: Flex__<typeof Dropdown>;
  frame7?: Flex__<"div">;
  loginMobile?: Flex__<"div">;
  frame8?: Flex__<"div">;
  frame10?: Flex__<"div">;
  scrollBar?: Flex__<"div">;
  jobCard?: Flex__<typeof JobCard>;
  map?: Flex__<typeof Map>;
  content?: Flex__<"div">;
  badgeGroup?: Flex__<"div">;
  message?: Flex__<"div">;
  trouvezUnJobNaJamaisEteAussiSimple?: Flex__<"div">;
  frame6?: Flex__<"div">;
  hero?: Flex__<"div">;
  benefices?: Flex__<"div">;
  container?: Flex__<"div">;
  content4?: Flex__<"div">;
  headingAndSupportingText?: Flex__<"div">;
  headingAndBadge?: Flex__<"div">;
  badgeGroup2?: Flex__<"div">;
  content2?: Flex__<"div">;
  message2?: Flex__<"div">;
  heading?: Flex__<"div">;
  supportingText?: Flex__<"div">;
  container2?: Flex__<"div">;
  content3?: Flex__<"div">;
  featureText?: Flex__<"div">;
  featuredIcon?: Flex__<"div">;
  textAndSupportingText?: Flex__<"div">;
  text9?: Flex__<"div">;
  supportingText2?: Flex__<"div">;
  featureText2?: Flex__<"div">;
  featuredIcon2?: Flex__<"div">;
  textAndSupportingText2?: Flex__<"div">;
  text10?: Flex__<"div">;
  supportingText3?: Flex__<"div">;
  featureText3?: Flex__<"div">;
  featuredIcon3?: Flex__<"div">;
  textAndSupportingText3?: Flex__<"div">;
  text11?: Flex__<"div">;
  supportingText4?: Flex__<"div">;
  footer?: Flex__<"div">;
  container3?: Flex__<"div">;
  content5?: Flex__<"div">;
  column?: Flex__<"div">;
  logo?: Flex__<"div">;
  companyLogo2?: Flex__<"div">;
  brand?: Flex__<"div">;
  socials?: Flex__<"div">;
  socialIcon?: Flex__<"div">;
  socialIcon2?: Flex__<"div">;
  footerLinksContainer2?: Flex__<"div">;
  footerLinksColumn3?: Flex__<"div">;
  heading4?: Flex__<"div">;
  footerLinks3?: Flex__<"div">;
  footerLink9?: Flex__<typeof Footerlink>;
  footerLink10?: Flex__<typeof Footerlink>;
  footerLink11?: Flex__<typeof Footerlink>;
  footerLink12?: Flex__<typeof Footerlink>;
  footerLink13?: Flex__<typeof Footerlink>;
  footerLinksColumn4?: Flex__<"div">;
  heading5?: Flex__<"div">;
  footerLinks4?: Flex__<"div">;
  footerLink14?: Flex__<typeof Footerlink>;
  footerLink15?: Flex__<typeof Footerlink>;
  footerLink16?: Flex__<typeof Footerlink>;
  container4?: Flex__<"div">;
  divider?: Flex__<"div">;
  content6?: Flex__<"div">;
  footerText?: Flex__<"div">;
  textbox?: Flex__<typeof TextInput>;
};

export interface DefaultAccueilProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAccueil__RenderFunc(props: {
  variants: PlasmicAccueil__VariantsArgs;
  args: PlasmicAccueil__ArgsType;
  overrides: PlasmicAccueil__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "lieu",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return undefined;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    componentData: usePlasmicDataOp(() => {
      return {
        sourceId: "kVSSe8ab4TtzwRPnTeEeUp",
        opId: "801a5603-e3bb-4b0f-8d97-1e00b2bc922e",
        userArgs: {},
        cacheKey: `plasmic.$.801a5603-e3bb-4b0f-8d97-1e00b2bc922e.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    getCompanyLocation: usePlasmicDataOp(() => {
      return {
        sourceId: "kVSSe8ab4TtzwRPnTeEeUp",
        opId: "7c6b5ebf-7cd0-4361-9cef-06aaee625412",
        userArgs: {},
        cacheKey: `plasmic.$.7c6b5ebf-7cd0-4361-9cef-06aaee625412.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    getJob: usePlasmicDataOp(() => {
      return {
        sourceId: "kVSSe8ab4TtzwRPnTeEeUp",
        opId: "fcaf755a-b63e-4e07-bb63-0ed2fd1dd76d",
        userArgs: {},
        cacheKey: `plasmic.$.fcaf755a-b63e-4e07-bb63-0ed2fd1dd76d.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshm8Nko4B5BDd()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"structureLp"}
            data-plasmic-override={overrides.structureLp}
            className={classNames(projectcss.all, sty.structureLp)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"nav"}
              data-plasmic-override={overrides.nav}
              hasGap={true}
              className={classNames(projectcss.all, sty.nav)}
            >
              <div
                data-plasmic-name={"frame"}
                data-plasmic-override={overrides.frame}
                className={classNames(projectcss.all, sty.frame)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__bpAp5)}>
                  <Group2Icon
                    className={classNames(projectcss.all, sty.svg__gIPn5)}
                    role={"img"}
                  />
                </div>
                <div
                  data-plasmic-name={"frame2"}
                  data-plasmic-override={overrides.frame2}
                  className={classNames(projectcss.all, sty.frame2)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame3"}
                    data-plasmic-override={overrides.frame3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ubshi
                      )}
                    >
                      {"JOB"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame4"}
                    data-plasmic-override={overrides.frame4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zQb3U
                      )}
                    >
                      {"AROUND"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame5"}
                    data-plasmic-override={overrides.frame5}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___56AkE
                      )}
                    >
                      {"ME"}
                    </div>
                  </Stack__>
                </div>
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"menuItems"}
                data-plasmic-override={overrides.menuItems}
                hasGap={true}
                className={classNames(projectcss.all, sty.menuItems)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vnokG
                  )}
                >
                  {"Services"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__k0Yf5
                  )}
                >
                  {"Offres"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mfuuY
                  )}
                >
                  {"Avis clients"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cAgp9
                  )}
                >
                  {"FAQ"}
                </div>
              </Stack__>
              <div className={classNames(projectcss.all, sty.freeBox__zjQXn)}>
                <Button
                  className={classNames("__wab_instance", sty.button__aaMjQ)}
                  icon={"none"}
                  iconImage={"/plasmic/jam_v_jean_loader/images/image11.svg"}
                  label={"Me connecter"}
                />
              </div>
            </Stack__>
            <div
              data-plasmic-name={"frame1437254391"}
              data-plasmic-override={overrides.frame1437254391}
              className={classNames(projectcss.all, sty.frame1437254391)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__luYmr)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/jam_v_jean_loader/images/image9.svg",
                  fullWidth: 1408,
                  fullHeight: 1365,
                  aspectRatio: 1.031502
                }}
              />

              <Stack__
                as={"div"}
                data-plasmic-name={"frame15"}
                data-plasmic-override={overrides.frame15}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame15)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"searchBar"}
                  data-plasmic-override={overrides.searchBar}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.searchBar)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame12"}
                    data-plasmic-override={overrides.frame12}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame12)}
                  >
                    <TextInput
                      data-plasmic-name={"textInput"}
                      data-plasmic-override={overrides.textInput}
                      className={classNames("__wab_instance", sty.textInput)}
                      iconUrl={"/plasmic/jam_v_jean_loader/images/image10.svg"}
                      onTextChange={async Lieu => {
                        const $steps = {};

                        $steps["updateLieu"] = true
                          ? (() => {
                              const actionArgs = {
                                variable: {
                                  objRoot: $state,
                                  variablePath: ["lieu"]
                                },
                                operation: 0
                              };
                              return (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;

                                $stateSet(objRoot, variablePath, value);
                                return value;
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["updateLieu"] != null &&
                          typeof $steps["updateLieu"] === "object" &&
                          typeof $steps["updateLieu"].then === "function"
                        ) {
                          $steps["updateLieu"] = await $steps["updateLieu"];
                        }
                      }}
                      type={"default"}
                    />

                    <TextInput
                      data-plasmic-name={"inputLieu"}
                      data-plasmic-override={overrides.inputLieu}
                      className={classNames("__wab_instance", sty.inputLieu)}
                      iconUrl={
                        "/plasmic/jam_v_jean_loader/images/phMapPinPng.png"
                      }
                      label={``}
                      onTextChange={async Lieu => {
                        const $steps = {};

                        $steps["updateLieu"] = true
                          ? (() => {
                              const actionArgs = {
                                variable: {
                                  objRoot: $state,
                                  variablePath: ["lieu"]
                                },
                                operation: 0,
                                value: VarInput
                              };
                              return (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;

                                $stateSet(objRoot, variablePath, value);
                                return value;
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["updateLieu"] != null &&
                          typeof $steps["updateLieu"] === "object" &&
                          typeof $steps["updateLieu"].then === "function"
                        ) {
                          $steps["updateLieu"] = await $steps["updateLieu"];
                        }
                      }}
                      type={"default"}
                    />

                    <Dropdown
                      data-plasmic-name={"dropdown"}
                      data-plasmic-override={overrides.dropdown}
                      className={classNames("__wab_instance", sty.dropdown)}
                      iconeUrl={"/plasmic/jam_v_jean_loader/images/image2.svg"}
                      label={``}
                      options={[
                        { key: "1", value: "Secteur d\u2019activit\u00e9" },
                        { key: "2", value: "Option 2" },
                        { key: "3", value: "Option 3" }
                      ]}
                    >
                      <Option
                        className={classNames(
                          "__wab_instance",
                          sty.option__ifCfd
                        )}
                        value={"Option 1"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___7SXKy
                          )}
                        >
                          {"Option 1"}
                        </div>
                      </Option>
                      <Option
                        className={classNames(
                          "__wab_instance",
                          sty.option__lkCyl
                        )}
                        value={"Option 2"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qs1Ay
                          )}
                        >
                          {"Option 2"}
                        </div>
                      </Option>
                    </Dropdown>
                    <Dropdown
                      data-plasmic-name={"dropdown3"}
                      data-plasmic-override={overrides.dropdown3}
                      className={classNames("__wab_instance", sty.dropdown3)}
                      iconeUrl={"/plasmic/jam_v_jean_loader/images/image3.svg"}
                      label={``}
                      options={[
                        { key: "1", value: "Disponibilit\u00e9" },
                        { key: "2", value: "Option 2" },
                        { key: "3", value: "Option 3" }
                      ]}
                    >
                      <Option
                        className={classNames(
                          "__wab_instance",
                          sty.option__ocncd
                        )}
                        value={"Option 1"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__chf8W
                          )}
                        >
                          {"Option 1"}
                        </div>
                      </Option>
                      <Option
                        className={classNames(
                          "__wab_instance",
                          sty.option__aDuVf
                        )}
                        value={"Option 2"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zHx0Z
                          )}
                        >
                          {"Option 2"}
                        </div>
                      </Option>
                    </Dropdown>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame14"}
                    data-plasmic-override={overrides.frame14}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame14)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame13"}
                      data-plasmic-override={overrides.frame13}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame13)}
                    >
                      <Dropdown
                        data-plasmic-name={"dropdown4"}
                        data-plasmic-override={overrides.dropdown4}
                        className={classNames("__wab_instance", sty.dropdown4)}
                        iconeUrl={
                          "/plasmic/jam_v_jean_loader/images/image7.svg"
                        }
                        label={``}
                        options={[
                          { key: "1", value: "Type de contrat" },
                          { key: "2", value: "Option 2" },
                          { key: "3", value: "Option 3" }
                        ]}
                      >
                        <Option
                          className={classNames(
                            "__wab_instance",
                            sty.option__tW8Cl
                          )}
                          value={"Option 1"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wBoK3
                            )}
                          >
                            {"Option 1"}
                          </div>
                        </Option>
                        <Option
                          className={classNames(
                            "__wab_instance",
                            sty.option__f6F6Y
                          )}
                          value={"Option 2"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__g3Tr9
                            )}
                          >
                            {"Option 2"}
                          </div>
                        </Option>
                      </Dropdown>
                      <Dropdown
                        data-plasmic-name={"dropdown5"}
                        data-plasmic-override={overrides.dropdown5}
                        className={classNames("__wab_instance", sty.dropdown5)}
                        iconeUrl={
                          "/plasmic/jam_v_jean_loader/images/image3.svg"
                        }
                        label={``}
                        options={[
                          { key: "1", value: "Temps de travail" },
                          { key: "2", value: "Option 2" },
                          { key: "3", value: "Option 3" }
                        ]}
                      >
                        <Option
                          className={classNames(
                            "__wab_instance",
                            sty.option___0AHoh
                          )}
                          value={"Option 1"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___4QWH
                            )}
                          >
                            {"Option 1"}
                          </div>
                        </Option>
                        <Option
                          className={classNames(
                            "__wab_instance",
                            sty.option__lkz9F
                          )}
                          value={"Option 2"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___4Pi5E
                            )}
                          >
                            {"Option 2"}
                          </div>
                        </Option>
                      </Dropdown>
                      <Dropdown
                        data-plasmic-name={"dropdown8"}
                        data-plasmic-override={overrides.dropdown8}
                        className={classNames("__wab_instance", sty.dropdown8)}
                        iconeUrl={
                          "/plasmic/jam_v_jean_loader/images/iconPhOfficeChair2.svg"
                        }
                        label={``}
                        options={[
                          { key: "1", value: "Mode de travail" },
                          { key: "2", value: "Option 2" },
                          { key: "3", value: "Option 3" }
                        ]}
                      >
                        <Option
                          className={classNames(
                            "__wab_instance",
                            sty.option__je1U8
                          )}
                          value={"Option 1"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ewckh
                            )}
                          >
                            {"Option 1"}
                          </div>
                        </Option>
                        <Option
                          className={classNames(
                            "__wab_instance",
                            sty.option__eAHx
                          )}
                          value={"Option 2"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___0AlgX
                            )}
                          >
                            {"Option 2"}
                          </div>
                        </Option>
                      </Dropdown>
                      <Dropdown
                        data-plasmic-name={"dropdown9"}
                        data-plasmic-override={overrides.dropdown9}
                        className={classNames("__wab_instance", sty.dropdown9)}
                        iconeUrl={
                          "/plasmic/jam_v_jean_loader/images/image5.svg"
                        }
                        label={``}
                        options={[
                          { key: "1", value: "Salaire" },
                          { key: "2", value: "Option 2" },
                          { key: "3", value: "Option 3" }
                        ]}
                      >
                        <Option
                          className={classNames(
                            "__wab_instance",
                            sty.option__hTkAo
                          )}
                          value={"Option 1"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___3TuK
                            )}
                          >
                            {"Option 1"}
                          </div>
                        </Option>
                        <Option
                          className={classNames(
                            "__wab_instance",
                            sty.option__qbGib
                          )}
                          value={"Option 2"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dxBqN
                            )}
                          >
                            {"Option 2"}
                          </div>
                        </Option>
                      </Dropdown>
                      <Dropdown
                        data-plasmic-name={"dropdown6"}
                        data-plasmic-override={overrides.dropdown6}
                        className={classNames("__wab_instance", sty.dropdown6)}
                        iconeUrl={
                          "/plasmic/jam_v_jean_loader/images/image4.svg"
                        }
                        label={``}
                        options={[
                          { key: "1", value: "Taille entreprise" },
                          { key: "2", value: "Option 2" },
                          { key: "3", value: "Option 3" }
                        ]}
                      >
                        <Option
                          className={classNames(
                            "__wab_instance",
                            sty.option__nzpbM
                          )}
                          value={"Option 1"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ntk8O
                            )}
                          >
                            {"Option 1"}
                          </div>
                        </Option>
                        <Option
                          className={classNames(
                            "__wab_instance",
                            sty.option__jgEyj
                          )}
                          value={"Option 2"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zTskh
                            )}
                          >
                            {"Option 2"}
                          </div>
                        </Option>
                      </Dropdown>
                    </Stack__>
                    <Button
                      className={classNames("__wab_instance", sty.button__sEVs)}
                      icon={"end"}
                      iconImage={
                        "/plasmic/jam_v_jean_loader/images/image11.svg"
                      }
                      label={"RECHERCHER"}
                    />
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame7"}
                  data-plasmic-override={overrides.frame7}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame7)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"loginMobile"}
                    data-plasmic-override={overrides.loginMobile}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.loginMobile)}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateLieu"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["lieu"]
                              },
                              operation: 0
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateLieu"] != null &&
                        typeof $steps["updateLieu"] === "object" &&
                        typeof $steps["updateLieu"].then === "function"
                      ) {
                        $steps["updateLieu"] = await $steps["updateLieu"];
                      }
                    }}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame8"}
                      data-plasmic-override={overrides.frame8}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame8)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame10"}
                        data-plasmic-override={overrides.frame10}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame10)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qLyJd
                          )}
                        >
                          {"Afficher la liste des r\u00e9sultats"}
                        </div>
                      </Stack__>
                      <div
                        data-plasmic-name={"scrollBar"}
                        data-plasmic-override={overrides.scrollBar}
                        className={classNames(projectcss.all, sty.scrollBar)}
                      />

                      {(_par =>
                        !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                        (() => {
                          try {
                            return $queries.getJob.data.map(
                              job => job["title"]
                            );
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return [];
                            }
                            throw e;
                          }
                        })()
                      ).map((__plasmic_item_0, __plasmic_idx_0) => {
                        const currentItem = __plasmic_item_0;
                        const currentIndex = __plasmic_idx_0;
                        return (
                          <JobCard
                            data-plasmic-name={"jobCard"}
                            data-plasmic-override={overrides.jobCard}
                            city={(() => {
                              try {
                                return $queries.getJob.data[currentIndex][
                                  "location"
                                ];
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                            className={classNames(
                              "__wab_instance",
                              sty.jobCard
                            )}
                            companyName={(() => {
                              try {
                                return $queries.getJob.data[currentIndex][
                                  "title"
                                ];
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                            customIcons={{}}
                            key={currentIndex}
                            state={"default"}
                            tags={[]}
                            title={(() => {
                              try {
                                return $queries.getJob.data[currentIndex][
                                  "title"
                                ];
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          />
                        );
                      })}
                    </Stack__>
                  </Stack__>
                  <Map
                    data-plasmic-name={"map"}
                    data-plasmic-override={overrides.map}
                    businesses={(() => {
                      try {
                        return $queries.getCompanyLocation.data.map(
                          company => ({
                            name: company.name,
                            location: company.location
                          })
                        );
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()}
                    className={classNames("__wab_instance", sty.map)}
                    mapStyle={
                      "mapbox://styles/scroll/cm6gi9ljw003t01s36b0jfl80"
                    }
                    searchAddress={(() => {
                      try {
                        return $state.lieu;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    zoom={15}
                  />
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"content"}
                data-plasmic-override={overrides.content}
                hasGap={true}
                className={classNames(projectcss.all, sty.content)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"badgeGroup"}
                  data-plasmic-override={overrides.badgeGroup}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.badgeGroup)}
                >
                  <div
                    data-plasmic-name={"message"}
                    data-plasmic-override={overrides.message}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.message
                    )}
                  >
                    {"Get ready to find a job"}
                  </div>
                </Stack__>
                <div
                  data-plasmic-name={"trouvezUnJobNaJamaisEteAussiSimple"}
                  data-plasmic-override={
                    overrides.trouvezUnJobNaJamaisEteAussiSimple
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.trouvezUnJobNaJamaisEteAussiSimple
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {"Trouvez un job n\u2019a jamais \u00e9t\u00e9 aussi "}
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#BBFE68" }}
                    >
                      {"simple"}
                    </span>
                    <React.Fragment> </React.Fragment>
                  </React.Fragment>
                </div>
              </Stack__>
              {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))([
                2, 3, 4
              ]).map((__plasmic_item_0, __plasmic_idx_0) => {
                const currentItem = __plasmic_item_0;
                const currentIndex = __plasmic_idx_0;
                return (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mx4Pf)}
                    key={currentIndex}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ayspk
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $queries.getCompanyLocation.data.map(
                              company => company.location
                            );
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </div>
                );
              })}
              <Stack__
                as={"div"}
                data-plasmic-name={"frame6"}
                data-plasmic-override={overrides.frame6}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame6)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"hero"}
                  data-plasmic-override={overrides.hero}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.hero)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mQghv
                    )}
                  >
                    {
                      "Trouvez facilement un emploi pr\u00e8s de chez vous et connectez-vous aux employeurs locaux."
                    }
                  </div>
                </Stack__>
              </Stack__>
            </div>
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"benefices"}
            data-plasmic-override={overrides.benefices}
            hasGap={true}
            className={classNames(projectcss.all, sty.benefices)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(projectcss.all, sty.container)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"content4"}
                data-plasmic-override={overrides.content4}
                hasGap={true}
                className={classNames(projectcss.all, sty.content4)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"headingAndSupportingText"}
                  data-plasmic-override={overrides.headingAndSupportingText}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    sty.headingAndSupportingText
                  )}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"headingAndBadge"}
                    data-plasmic-override={overrides.headingAndBadge}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.headingAndBadge)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"badgeGroup2"}
                      data-plasmic-override={overrides.badgeGroup2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.badgeGroup2)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"content2"}
                        data-plasmic-override={overrides.content2}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.content2)}
                      >
                        <div
                          data-plasmic-name={"message2"}
                          data-plasmic-override={overrides.message2}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.message2
                          )}
                        >
                          {"Notre solution"}
                        </div>
                      </Stack__>
                    </Stack__>
                    <div
                      data-plasmic-name={"heading"}
                      data-plasmic-override={overrides.heading}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.heading
                      )}
                    >
                      {"B\u00e9n\u00e9fices pour vos clients"}
                    </div>
                  </Stack__>
                  <div
                    data-plasmic-name={"supportingText"}
                    data-plasmic-override={overrides.supportingText}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.supportingText
                    )}
                  >
                    {
                      "D\u00e9crivez les avantages que vos services apportent \u00e0 vos clients"
                    }
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"container2"}
              data-plasmic-override={overrides.container2}
              hasGap={true}
              className={classNames(projectcss.all, sty.container2)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"content3"}
                data-plasmic-override={overrides.content3}
                hasGap={true}
                className={classNames(projectcss.all, sty.content3)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"featureText"}
                  data-plasmic-override={overrides.featureText}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.featureText)}
                >
                  <div
                    data-plasmic-name={"featuredIcon"}
                    data-plasmic-override={overrides.featuredIcon}
                    className={classNames(projectcss.all, sty.featuredIcon)}
                  >
                    <Mail2Icon
                      className={classNames(projectcss.all, sty.svg__i5XF5)}
                      role={"img"}
                    />
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"textAndSupportingText"}
                    data-plasmic-override={overrides.textAndSupportingText}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.textAndSupportingText
                    )}
                  >
                    <div
                      data-plasmic-name={"text9"}
                      data-plasmic-override={overrides.text9}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text9
                      )}
                    >
                      {"B\u00e9n\u00e9fice 1"}
                    </div>
                    <div
                      data-plasmic-name={"supportingText2"}
                      data-plasmic-override={overrides.supportingText2}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.supportingText2
                      )}
                    >
                      {
                        "Give one sentence describing who this is for and what it helps them achieve"
                      }
                    </div>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__xhGdy
                      )}
                      icon={"none"}
                      iconImage={
                        "/plasmic/jam_v_jean_loader/images/image11.svg"
                      }
                      label={"En savoir plus ->"}
                    />
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"featureText2"}
                  data-plasmic-override={overrides.featureText2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.featureText2)}
                >
                  <div
                    data-plasmic-name={"featuredIcon2"}
                    data-plasmic-override={overrides.featuredIcon2}
                    className={classNames(projectcss.all, sty.featuredIcon2)}
                  >
                    <ZapIcon
                      className={classNames(projectcss.all, sty.svg__cb5P7)}
                      role={"img"}
                    />
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"textAndSupportingText2"}
                    data-plasmic-override={overrides.textAndSupportingText2}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.textAndSupportingText2
                    )}
                  >
                    <div
                      data-plasmic-name={"text10"}
                      data-plasmic-override={overrides.text10}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text10
                      )}
                    >
                      {"B\u00e9n\u00e9fice 2"}
                    </div>
                    <div
                      data-plasmic-name={"supportingText3"}
                      data-plasmic-override={overrides.supportingText3}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.supportingText3
                      )}
                    >
                      {
                        "Give one sentence describing who this is for and what it helps them achieve"
                      }
                    </div>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__nw543
                      )}
                      icon={"none"}
                      iconImage={
                        "/plasmic/jam_v_jean_loader/images/image11.svg"
                      }
                      label={"En savoir plus ->"}
                    />
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"featureText3"}
                  data-plasmic-override={overrides.featureText3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.featureText3)}
                >
                  <div
                    data-plasmic-name={"featuredIcon3"}
                    data-plasmic-override={overrides.featuredIcon3}
                    className={classNames(projectcss.all, sty.featuredIcon3)}
                  >
                    <BarChart2Icon
                      className={classNames(projectcss.all, sty.svg__hyJvG)}
                      role={"img"}
                    />
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"textAndSupportingText3"}
                    data-plasmic-override={overrides.textAndSupportingText3}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.textAndSupportingText3
                    )}
                  >
                    <div
                      data-plasmic-name={"text11"}
                      data-plasmic-override={overrides.text11}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text11
                      )}
                    >
                      {"B\u00e9n\u00e9fice 3"}
                    </div>
                    <div
                      data-plasmic-name={"supportingText4"}
                      data-plasmic-override={overrides.supportingText4}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.supportingText4
                      )}
                    >
                      {
                        "Give one sentence describing who this is for and what it helps them achieve"
                      }
                    </div>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__fYeg1
                      )}
                      icon={"none"}
                      iconImage={
                        "/plasmic/jam_v_jean_loader/images/image11.svg"
                      }
                      label={"En savoir plus ->"}
                    />
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            hasGap={true}
            className={classNames(projectcss.all, sty.footer)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              hasGap={true}
              className={classNames(projectcss.all, sty.container3)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"content5"}
                data-plasmic-override={overrides.content5}
                hasGap={true}
                className={classNames(projectcss.all, sty.content5)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"column"}
                  data-plasmic-override={overrides.column}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"logo"}
                    data-plasmic-override={overrides.logo}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.logo)}
                  >
                    <div
                      data-plasmic-name={"companyLogo2"}
                      data-plasmic-override={overrides.companyLogo2}
                      className={classNames(projectcss.all, sty.companyLogo2)}
                    >
                      <div
                        data-plasmic-name={"brand"}
                        data-plasmic-override={overrides.brand}
                        className={classNames(projectcss.all, sty.brand)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vIFa
                          )}
                        >
                          {"Brand"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"socials"}
                    data-plasmic-override={overrides.socials}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.socials)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__nxcxM)}
                      displayHeight={"24px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"24px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/jam_v_jean_loader/images/socialIcon3.svg",
                        fullWidth: 24,
                        fullHeight: 24,
                        aspectRatio: 1
                      }}
                    />

                    <SocialIcon2Icon
                      className={classNames(projectcss.all, sty.svg__hysT4)}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"socialIcon"}
                      data-plasmic-override={overrides.socialIcon}
                      className={classNames(projectcss.all, sty.socialIcon)}
                    >
                      <Group3Icon
                        className={classNames(projectcss.all, sty.svg__eMVfe)}
                        role={"img"}
                      />
                    </div>
                    <div
                      data-plasmic-name={"socialIcon2"}
                      data-plasmic-override={overrides.socialIcon2}
                      className={classNames(projectcss.all, sty.socialIcon2)}
                    >
                      <Group4Icon
                        className={classNames(projectcss.all, sty.svg__su3OB)}
                        role={"img"}
                      />
                    </div>
                  </Stack__>
                </Stack__>
                <div
                  data-plasmic-name={"footerLinksContainer2"}
                  data-plasmic-override={overrides.footerLinksContainer2}
                  className={classNames(
                    projectcss.all,
                    sty.footerLinksContainer2
                  )}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"footerLinksColumn3"}
                    data-plasmic-override={overrides.footerLinksColumn3}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.footerLinksColumn3
                    )}
                  >
                    <div
                      data-plasmic-name={"heading4"}
                      data-plasmic-override={overrides.heading4}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.heading4
                      )}
                    >
                      {"Info"}
                    </div>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"footerLinks3"}
                      data-plasmic-override={overrides.footerLinks3}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.footerLinks3)}
                    >
                      <Footerlink
                        data-plasmic-name={"footerLink9"}
                        data-plasmic-override={overrides.footerLink9}
                        className={classNames(
                          "__wab_instance",
                          sty.footerLink9
                        )}
                        text={"Services"}
                      />

                      <Footerlink
                        data-plasmic-name={"footerLink10"}
                        data-plasmic-override={overrides.footerLink10}
                        className={classNames(
                          "__wab_instance",
                          sty.footerLink10
                        )}
                        text={"Offres"}
                      />

                      <Footerlink
                        data-plasmic-name={"footerLink11"}
                        data-plasmic-override={overrides.footerLink11}
                        className={classNames(
                          "__wab_instance",
                          sty.footerLink11
                        )}
                        text={"Avis Clients"}
                      />

                      <Footerlink
                        data-plasmic-name={"footerLink12"}
                        data-plasmic-override={overrides.footerLink12}
                        className={classNames(
                          "__wab_instance",
                          sty.footerLink12
                        )}
                        text={"FAQ"}
                      />

                      <Footerlink
                        data-plasmic-name={"footerLink13"}
                        data-plasmic-override={overrides.footerLink13}
                        className={classNames(
                          "__wab_instance",
                          sty.footerLink13
                        )}
                        text={"Contact"}
                      />
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"footerLinksColumn4"}
                    data-plasmic-override={overrides.footerLinksColumn4}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.footerLinksColumn4
                    )}
                  >
                    <div
                      data-plasmic-name={"heading5"}
                      data-plasmic-override={overrides.heading5}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.heading5
                      )}
                    >
                      {"Legal"}
                    </div>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"footerLinks4"}
                      data-plasmic-override={overrides.footerLinks4}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.footerLinks4)}
                    >
                      <Footerlink
                        data-plasmic-name={"footerLink14"}
                        data-plasmic-override={overrides.footerLink14}
                        className={classNames(
                          "__wab_instance",
                          sty.footerLink14
                        )}
                        text={"Mentions l\u00e9gales"}
                      />

                      <Footerlink
                        data-plasmic-name={"footerLink15"}
                        data-plasmic-override={overrides.footerLink15}
                        className={classNames(
                          "__wab_instance",
                          sty.footerLink15
                        )}
                        text={"Politique de confidentialit\u00e9"}
                      />

                      <Footerlink
                        data-plasmic-name={"footerLink16"}
                        data-plasmic-override={overrides.footerLink16}
                        className={classNames(
                          "__wab_instance",
                          sty.footerLink16
                        )}
                        text={"CGU/CGV"}
                      />
                    </Stack__>
                  </Stack__>
                </div>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              hasGap={true}
              className={classNames(projectcss.all, sty.container4)}
            >
              <div
                data-plasmic-name={"divider"}
                data-plasmic-override={overrides.divider}
                className={classNames(projectcss.all, sty.divider)}
              />

              <div
                data-plasmic-name={"content6"}
                data-plasmic-override={overrides.content6}
                className={classNames(projectcss.all, sty.content6)}
              >
                <div
                  data-plasmic-name={"footerText"}
                  data-plasmic-override={overrides.footerText}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.footerText
                  )}
                >
                  {"\u00a9 2024 Job around me. Site designer par Scroll."}
                </div>
              </div>
            </Stack__>
          </Stack__>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "structureLp",
    "nav",
    "frame",
    "frame2",
    "frame3",
    "frame4",
    "frame5",
    "menuItems",
    "frame1437254391",
    "frame15",
    "searchBar",
    "frame12",
    "textInput",
    "textbox",
    "inputLieu",
    "dropdown",
    "dropdown3",
    "frame14",
    "frame13",
    "dropdown4",
    "dropdown5",
    "dropdown8",
    "dropdown9",
    "dropdown6",
    "frame7",
    "loginMobile",
    "frame8",
    "frame10",
    "scrollBar",
    "jobCard",
    "map",
    "content",
    "badgeGroup",
    "message",
    "trouvezUnJobNaJamaisEteAussiSimple",
    "frame6",
    "hero",
    "benefices",
    "container",
    "content4",
    "headingAndSupportingText",
    "headingAndBadge",
    "badgeGroup2",
    "content2",
    "message2",
    "heading",
    "supportingText",
    "container2",
    "content3",
    "featureText",
    "featuredIcon",
    "textAndSupportingText",
    "text9",
    "supportingText2",
    "featureText2",
    "featuredIcon2",
    "textAndSupportingText2",
    "text10",
    "supportingText3",
    "featureText3",
    "featuredIcon3",
    "textAndSupportingText3",
    "text11",
    "supportingText4",
    "footer",
    "container3",
    "content5",
    "column",
    "logo",
    "companyLogo2",
    "brand",
    "socials",
    "socialIcon",
    "socialIcon2",
    "footerLinksContainer2",
    "footerLinksColumn3",
    "heading4",
    "footerLinks3",
    "footerLink9",
    "footerLink10",
    "footerLink11",
    "footerLink12",
    "footerLink13",
    "footerLinksColumn4",
    "heading5",
    "footerLinks4",
    "footerLink14",
    "footerLink15",
    "footerLink16",
    "container4",
    "divider",
    "content6",
    "footerText"
  ],
  structureLp: [
    "structureLp",
    "nav",
    "frame",
    "frame2",
    "frame3",
    "frame4",
    "frame5",
    "menuItems",
    "frame1437254391",
    "frame15",
    "searchBar",
    "frame12",
    "textInput",
    "textbox",
    "inputLieu",
    "dropdown",
    "dropdown3",
    "frame14",
    "frame13",
    "dropdown4",
    "dropdown5",
    "dropdown8",
    "dropdown9",
    "dropdown6",
    "frame7",
    "loginMobile",
    "frame8",
    "frame10",
    "scrollBar",
    "jobCard",
    "map",
    "content",
    "badgeGroup",
    "message",
    "trouvezUnJobNaJamaisEteAussiSimple",
    "frame6",
    "hero"
  ],
  nav: ["nav", "frame", "frame2", "frame3", "frame4", "frame5", "menuItems"],
  frame: ["frame", "frame2", "frame3", "frame4", "frame5"],
  frame2: ["frame2", "frame3", "frame4", "frame5"],
  frame3: ["frame3"],
  frame4: ["frame4"],
  frame5: ["frame5"],
  menuItems: ["menuItems"],
  frame1437254391: [
    "frame1437254391",
    "frame15",
    "searchBar",
    "frame12",
    "textInput",
    "textbox",
    "inputLieu",
    "dropdown",
    "dropdown3",
    "frame14",
    "frame13",
    "dropdown4",
    "dropdown5",
    "dropdown8",
    "dropdown9",
    "dropdown6",
    "frame7",
    "loginMobile",
    "frame8",
    "frame10",
    "scrollBar",
    "jobCard",
    "map",
    "content",
    "badgeGroup",
    "message",
    "trouvezUnJobNaJamaisEteAussiSimple",
    "frame6",
    "hero"
  ],
  frame15: [
    "frame15",
    "searchBar",
    "frame12",
    "textInput",
    "textbox",
    "inputLieu",
    "dropdown",
    "dropdown3",
    "frame14",
    "frame13",
    "dropdown4",
    "dropdown5",
    "dropdown8",
    "dropdown9",
    "dropdown6",
    "frame7",
    "loginMobile",
    "frame8",
    "frame10",
    "scrollBar",
    "jobCard",
    "map"
  ],
  searchBar: [
    "searchBar",
    "frame12",
    "textInput",
    "textbox",
    "inputLieu",
    "dropdown",
    "dropdown3",
    "frame14",
    "frame13",
    "dropdown4",
    "dropdown5",
    "dropdown8",
    "dropdown9",
    "dropdown6"
  ],
  frame12: [
    "frame12",
    "textInput",
    "textbox",
    "inputLieu",
    "dropdown",
    "dropdown3"
  ],
  textInput: ["textInput", "textbox"],
  inputLieu: ["inputLieu"],
  dropdown: ["dropdown"],
  dropdown3: ["dropdown3"],
  frame14: [
    "frame14",
    "frame13",
    "dropdown4",
    "dropdown5",
    "dropdown8",
    "dropdown9",
    "dropdown6"
  ],
  frame13: [
    "frame13",
    "dropdown4",
    "dropdown5",
    "dropdown8",
    "dropdown9",
    "dropdown6"
  ],
  dropdown4: ["dropdown4"],
  dropdown5: ["dropdown5"],
  dropdown8: ["dropdown8"],
  dropdown9: ["dropdown9"],
  dropdown6: ["dropdown6"],
  frame7: [
    "frame7",
    "loginMobile",
    "frame8",
    "frame10",
    "scrollBar",
    "jobCard",
    "map"
  ],
  loginMobile: ["loginMobile", "frame8", "frame10", "scrollBar", "jobCard"],
  frame8: ["frame8", "frame10", "scrollBar", "jobCard"],
  frame10: ["frame10"],
  scrollBar: ["scrollBar"],
  jobCard: ["jobCard"],
  map: ["map"],
  content: [
    "content",
    "badgeGroup",
    "message",
    "trouvezUnJobNaJamaisEteAussiSimple"
  ],
  badgeGroup: ["badgeGroup", "message"],
  message: ["message"],
  trouvezUnJobNaJamaisEteAussiSimple: ["trouvezUnJobNaJamaisEteAussiSimple"],
  frame6: ["frame6", "hero"],
  hero: ["hero"],
  benefices: [
    "benefices",
    "container",
    "content4",
    "headingAndSupportingText",
    "headingAndBadge",
    "badgeGroup2",
    "content2",
    "message2",
    "heading",
    "supportingText",
    "container2",
    "content3",
    "featureText",
    "featuredIcon",
    "textAndSupportingText",
    "text9",
    "supportingText2",
    "featureText2",
    "featuredIcon2",
    "textAndSupportingText2",
    "text10",
    "supportingText3",
    "featureText3",
    "featuredIcon3",
    "textAndSupportingText3",
    "text11",
    "supportingText4"
  ],
  container: [
    "container",
    "content4",
    "headingAndSupportingText",
    "headingAndBadge",
    "badgeGroup2",
    "content2",
    "message2",
    "heading",
    "supportingText"
  ],
  content4: [
    "content4",
    "headingAndSupportingText",
    "headingAndBadge",
    "badgeGroup2",
    "content2",
    "message2",
    "heading",
    "supportingText"
  ],
  headingAndSupportingText: [
    "headingAndSupportingText",
    "headingAndBadge",
    "badgeGroup2",
    "content2",
    "message2",
    "heading",
    "supportingText"
  ],
  headingAndBadge: [
    "headingAndBadge",
    "badgeGroup2",
    "content2",
    "message2",
    "heading"
  ],
  badgeGroup2: ["badgeGroup2", "content2", "message2"],
  content2: ["content2", "message2"],
  message2: ["message2"],
  heading: ["heading"],
  supportingText: ["supportingText"],
  container2: [
    "container2",
    "content3",
    "featureText",
    "featuredIcon",
    "textAndSupportingText",
    "text9",
    "supportingText2",
    "featureText2",
    "featuredIcon2",
    "textAndSupportingText2",
    "text10",
    "supportingText3",
    "featureText3",
    "featuredIcon3",
    "textAndSupportingText3",
    "text11",
    "supportingText4"
  ],
  content3: [
    "content3",
    "featureText",
    "featuredIcon",
    "textAndSupportingText",
    "text9",
    "supportingText2",
    "featureText2",
    "featuredIcon2",
    "textAndSupportingText2",
    "text10",
    "supportingText3",
    "featureText3",
    "featuredIcon3",
    "textAndSupportingText3",
    "text11",
    "supportingText4"
  ],
  featureText: [
    "featureText",
    "featuredIcon",
    "textAndSupportingText",
    "text9",
    "supportingText2"
  ],
  featuredIcon: ["featuredIcon"],
  textAndSupportingText: ["textAndSupportingText", "text9", "supportingText2"],
  text9: ["text9"],
  supportingText2: ["supportingText2"],
  featureText2: [
    "featureText2",
    "featuredIcon2",
    "textAndSupportingText2",
    "text10",
    "supportingText3"
  ],
  featuredIcon2: ["featuredIcon2"],
  textAndSupportingText2: [
    "textAndSupportingText2",
    "text10",
    "supportingText3"
  ],
  text10: ["text10"],
  supportingText3: ["supportingText3"],
  featureText3: [
    "featureText3",
    "featuredIcon3",
    "textAndSupportingText3",
    "text11",
    "supportingText4"
  ],
  featuredIcon3: ["featuredIcon3"],
  textAndSupportingText3: [
    "textAndSupportingText3",
    "text11",
    "supportingText4"
  ],
  text11: ["text11"],
  supportingText4: ["supportingText4"],
  footer: [
    "footer",
    "container3",
    "content5",
    "column",
    "logo",
    "companyLogo2",
    "brand",
    "socials",
    "socialIcon",
    "socialIcon2",
    "footerLinksContainer2",
    "footerLinksColumn3",
    "heading4",
    "footerLinks3",
    "footerLink9",
    "footerLink10",
    "footerLink11",
    "footerLink12",
    "footerLink13",
    "footerLinksColumn4",
    "heading5",
    "footerLinks4",
    "footerLink14",
    "footerLink15",
    "footerLink16",
    "container4",
    "divider",
    "content6",
    "footerText"
  ],
  container3: [
    "container3",
    "content5",
    "column",
    "logo",
    "companyLogo2",
    "brand",
    "socials",
    "socialIcon",
    "socialIcon2",
    "footerLinksContainer2",
    "footerLinksColumn3",
    "heading4",
    "footerLinks3",
    "footerLink9",
    "footerLink10",
    "footerLink11",
    "footerLink12",
    "footerLink13",
    "footerLinksColumn4",
    "heading5",
    "footerLinks4",
    "footerLink14",
    "footerLink15",
    "footerLink16"
  ],
  content5: [
    "content5",
    "column",
    "logo",
    "companyLogo2",
    "brand",
    "socials",
    "socialIcon",
    "socialIcon2",
    "footerLinksContainer2",
    "footerLinksColumn3",
    "heading4",
    "footerLinks3",
    "footerLink9",
    "footerLink10",
    "footerLink11",
    "footerLink12",
    "footerLink13",
    "footerLinksColumn4",
    "heading5",
    "footerLinks4",
    "footerLink14",
    "footerLink15",
    "footerLink16"
  ],
  column: [
    "column",
    "logo",
    "companyLogo2",
    "brand",
    "socials",
    "socialIcon",
    "socialIcon2"
  ],
  logo: ["logo", "companyLogo2", "brand"],
  companyLogo2: ["companyLogo2", "brand"],
  brand: ["brand"],
  socials: ["socials", "socialIcon", "socialIcon2"],
  socialIcon: ["socialIcon"],
  socialIcon2: ["socialIcon2"],
  footerLinksContainer2: [
    "footerLinksContainer2",
    "footerLinksColumn3",
    "heading4",
    "footerLinks3",
    "footerLink9",
    "footerLink10",
    "footerLink11",
    "footerLink12",
    "footerLink13",
    "footerLinksColumn4",
    "heading5",
    "footerLinks4",
    "footerLink14",
    "footerLink15",
    "footerLink16"
  ],
  footerLinksColumn3: [
    "footerLinksColumn3",
    "heading4",
    "footerLinks3",
    "footerLink9",
    "footerLink10",
    "footerLink11",
    "footerLink12",
    "footerLink13"
  ],
  heading4: ["heading4"],
  footerLinks3: [
    "footerLinks3",
    "footerLink9",
    "footerLink10",
    "footerLink11",
    "footerLink12",
    "footerLink13"
  ],
  footerLink9: ["footerLink9"],
  footerLink10: ["footerLink10"],
  footerLink11: ["footerLink11"],
  footerLink12: ["footerLink12"],
  footerLink13: ["footerLink13"],
  footerLinksColumn4: [
    "footerLinksColumn4",
    "heading5",
    "footerLinks4",
    "footerLink14",
    "footerLink15",
    "footerLink16"
  ],
  heading5: ["heading5"],
  footerLinks4: [
    "footerLinks4",
    "footerLink14",
    "footerLink15",
    "footerLink16"
  ],
  footerLink14: ["footerLink14"],
  footerLink15: ["footerLink15"],
  footerLink16: ["footerLink16"],
  container4: ["container4", "divider", "content6", "footerText"],
  divider: ["divider"],
  content6: ["content6", "footerText"],
  footerText: ["footerText"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  structureLp: "div";
  nav: "div";
  frame: "div";
  frame2: "div";
  frame3: "div";
  frame4: "div";
  frame5: "div";
  menuItems: "div";
  frame1437254391: "div";
  frame15: "div";
  searchBar: "div";
  frame12: "div";
  textInput: typeof TextInput;
  inputLieu: typeof TextInput;
  dropdown: typeof Dropdown;
  dropdown3: typeof Dropdown;
  frame14: "div";
  frame13: "div";
  dropdown4: typeof Dropdown;
  dropdown5: typeof Dropdown;
  dropdown8: typeof Dropdown;
  dropdown9: typeof Dropdown;
  dropdown6: typeof Dropdown;
  frame7: "div";
  loginMobile: "div";
  frame8: "div";
  frame10: "div";
  scrollBar: "div";
  jobCard: typeof JobCard;
  map: typeof Map;
  content: "div";
  badgeGroup: "div";
  message: "div";
  trouvezUnJobNaJamaisEteAussiSimple: "div";
  frame6: "div";
  hero: "div";
  benefices: "div";
  container: "div";
  content4: "div";
  headingAndSupportingText: "div";
  headingAndBadge: "div";
  badgeGroup2: "div";
  content2: "div";
  message2: "div";
  heading: "div";
  supportingText: "div";
  container2: "div";
  content3: "div";
  featureText: "div";
  featuredIcon: "div";
  textAndSupportingText: "div";
  text9: "div";
  supportingText2: "div";
  featureText2: "div";
  featuredIcon2: "div";
  textAndSupportingText2: "div";
  text10: "div";
  supportingText3: "div";
  featureText3: "div";
  featuredIcon3: "div";
  textAndSupportingText3: "div";
  text11: "div";
  supportingText4: "div";
  footer: "div";
  container3: "div";
  content5: "div";
  column: "div";
  logo: "div";
  companyLogo2: "div";
  brand: "div";
  socials: "div";
  socialIcon: "div";
  socialIcon2: "div";
  footerLinksContainer2: "div";
  footerLinksColumn3: "div";
  heading4: "div";
  footerLinks3: "div";
  footerLink9: typeof Footerlink;
  footerLink10: typeof Footerlink;
  footerLink11: typeof Footerlink;
  footerLink12: typeof Footerlink;
  footerLink13: typeof Footerlink;
  footerLinksColumn4: "div";
  heading5: "div";
  footerLinks4: "div";
  footerLink14: typeof Footerlink;
  footerLink15: typeof Footerlink;
  footerLink16: typeof Footerlink;
  container4: "div";
  divider: "div";
  content6: "div";
  footerText: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAccueil__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAccueil__VariantsArgs;
    args?: PlasmicAccueil__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAccueil__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAccueil__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAccueil__ArgProps,
          internalVariantPropNames: PlasmicAccueil__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAccueil__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAccueil";
  } else {
    func.displayName = `PlasmicAccueil.${nodeName}`;
  }
  return func;
}

export const PlasmicAccueil = Object.assign(
  // Top-level PlasmicAccueil renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    structureLp: makeNodeComponent("structureLp"),
    nav: makeNodeComponent("nav"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    frame3: makeNodeComponent("frame3"),
    frame4: makeNodeComponent("frame4"),
    frame5: makeNodeComponent("frame5"),
    menuItems: makeNodeComponent("menuItems"),
    frame1437254391: makeNodeComponent("frame1437254391"),
    frame15: makeNodeComponent("frame15"),
    searchBar: makeNodeComponent("searchBar"),
    frame12: makeNodeComponent("frame12"),
    textInput: makeNodeComponent("textInput"),
    inputLieu: makeNodeComponent("inputLieu"),
    dropdown: makeNodeComponent("dropdown"),
    dropdown3: makeNodeComponent("dropdown3"),
    frame14: makeNodeComponent("frame14"),
    frame13: makeNodeComponent("frame13"),
    dropdown4: makeNodeComponent("dropdown4"),
    dropdown5: makeNodeComponent("dropdown5"),
    dropdown8: makeNodeComponent("dropdown8"),
    dropdown9: makeNodeComponent("dropdown9"),
    dropdown6: makeNodeComponent("dropdown6"),
    frame7: makeNodeComponent("frame7"),
    loginMobile: makeNodeComponent("loginMobile"),
    frame8: makeNodeComponent("frame8"),
    frame10: makeNodeComponent("frame10"),
    scrollBar: makeNodeComponent("scrollBar"),
    jobCard: makeNodeComponent("jobCard"),
    map: makeNodeComponent("map"),
    content: makeNodeComponent("content"),
    badgeGroup: makeNodeComponent("badgeGroup"),
    message: makeNodeComponent("message"),
    trouvezUnJobNaJamaisEteAussiSimple: makeNodeComponent(
      "trouvezUnJobNaJamaisEteAussiSimple"
    ),
    frame6: makeNodeComponent("frame6"),
    hero: makeNodeComponent("hero"),
    benefices: makeNodeComponent("benefices"),
    container: makeNodeComponent("container"),
    content4: makeNodeComponent("content4"),
    headingAndSupportingText: makeNodeComponent("headingAndSupportingText"),
    headingAndBadge: makeNodeComponent("headingAndBadge"),
    badgeGroup2: makeNodeComponent("badgeGroup2"),
    content2: makeNodeComponent("content2"),
    message2: makeNodeComponent("message2"),
    heading: makeNodeComponent("heading"),
    supportingText: makeNodeComponent("supportingText"),
    container2: makeNodeComponent("container2"),
    content3: makeNodeComponent("content3"),
    featureText: makeNodeComponent("featureText"),
    featuredIcon: makeNodeComponent("featuredIcon"),
    textAndSupportingText: makeNodeComponent("textAndSupportingText"),
    text9: makeNodeComponent("text9"),
    supportingText2: makeNodeComponent("supportingText2"),
    featureText2: makeNodeComponent("featureText2"),
    featuredIcon2: makeNodeComponent("featuredIcon2"),
    textAndSupportingText2: makeNodeComponent("textAndSupportingText2"),
    text10: makeNodeComponent("text10"),
    supportingText3: makeNodeComponent("supportingText3"),
    featureText3: makeNodeComponent("featureText3"),
    featuredIcon3: makeNodeComponent("featuredIcon3"),
    textAndSupportingText3: makeNodeComponent("textAndSupportingText3"),
    text11: makeNodeComponent("text11"),
    supportingText4: makeNodeComponent("supportingText4"),
    footer: makeNodeComponent("footer"),
    container3: makeNodeComponent("container3"),
    content5: makeNodeComponent("content5"),
    column: makeNodeComponent("column"),
    logo: makeNodeComponent("logo"),
    companyLogo2: makeNodeComponent("companyLogo2"),
    brand: makeNodeComponent("brand"),
    socials: makeNodeComponent("socials"),
    socialIcon: makeNodeComponent("socialIcon"),
    socialIcon2: makeNodeComponent("socialIcon2"),
    footerLinksContainer2: makeNodeComponent("footerLinksContainer2"),
    footerLinksColumn3: makeNodeComponent("footerLinksColumn3"),
    heading4: makeNodeComponent("heading4"),
    footerLinks3: makeNodeComponent("footerLinks3"),
    footerLink9: makeNodeComponent("footerLink9"),
    footerLink10: makeNodeComponent("footerLink10"),
    footerLink11: makeNodeComponent("footerLink11"),
    footerLink12: makeNodeComponent("footerLink12"),
    footerLink13: makeNodeComponent("footerLink13"),
    footerLinksColumn4: makeNodeComponent("footerLinksColumn4"),
    heading5: makeNodeComponent("heading5"),
    footerLinks4: makeNodeComponent("footerLinks4"),
    footerLink14: makeNodeComponent("footerLink14"),
    footerLink15: makeNodeComponent("footerLink15"),
    footerLink16: makeNodeComponent("footerLink16"),
    container4: makeNodeComponent("container4"),
    divider: makeNodeComponent("divider"),
    content6: makeNodeComponent("content6"),
    footerText: makeNodeComponent("footerText"),

    // Metadata about props expected for PlasmicAccueil
    internalVariantProps: PlasmicAccueil__VariantProps,
    internalArgProps: PlasmicAccueil__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAccueil;
/* prettier-ignore-end */
