// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f7DE9y7qp46fyCw5nuY8f9
// Component: GALpJ_8ZdkdW

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { TextInput } from "../../TextInput"; // plasmic-import: vyWUomJMQins/codeComponent
import { PhoneSelector } from "../../PhoneSelector/PhoneSelector"; // plasmic-import: sOyePdANTQ6t/codeComponent
import { CheckBox } from "../../CheckBox"; // plasmic-import: 6TZuO3lDLJXU/codeComponent
import { Button } from "../../Button"; // plasmic-import: NvY5LE-Ew6FA/codeComponent
import { TextLink } from "../../TextLink"; // plasmic-import: uTXJO5H_7wRR/codeComponent

import { useScreenVariants as useScreenVariantshm8Nko4B5BDd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: HM8Nko4B5BDd/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: f7DE9y7qp46fyCw5nuY8f9/projectcss
import sty from "./PlasmicInscription.module.css"; // plasmic-import: GALpJ_8ZdkdW/css

import PictogramIcon from "./icons/PlasmicIcon__Pictogram"; // plasmic-import: KlZQiGxQTluF/icon
import DividerLineIcon from "./icons/PlasmicIcon__DividerLine"; // plasmic-import: VvHpOw2n2MiA/icon

createPlasmicElementProxy;

export type PlasmicInscription__VariantMembers = {};
export type PlasmicInscription__VariantsArgs = {};
type VariantPropType = keyof PlasmicInscription__VariantsArgs;
export const PlasmicInscription__VariantProps = new Array<VariantPropType>();

export type PlasmicInscription__ArgsType = {};
type ArgPropType = keyof PlasmicInscription__ArgsType;
export const PlasmicInscription__ArgProps = new Array<ArgPropType>();

export type PlasmicInscription__OverridesType = {
  inscription?: Flex__<"div">;
  signUp?: Flex__<"div">;
  imageWrapper?: Flex__<"div">;
  logoWrapper?: Flex__<"div">;
  baseline?: Flex__<"div">;
  frame?: Flex__<"div">;
  frame2?: Flex__<"div">;
  frame3?: Flex__<"div">;
  formWrapper?: Flex__<"div">;
  form?: Flex__<"div">;
  title?: Flex__<"div">;
  heading?: Flex__<"div">;
  inputWrapper?: Flex__<"div">;
  textInput?: Flex__<typeof TextInput>;
  textInput2?: Flex__<typeof TextInput>;
  inputWrapper2?: Flex__<"div">;
  textInput3?: Flex__<typeof TextInput>;
  inputWrapper3?: Flex__<"div">;
  label?: Flex__<"div">;
  inputWrapper4?: Flex__<"div">;
  phoneSelector?: Flex__<typeof PhoneSelector>;
  textInput4?: Flex__<typeof TextInput>;
  inputWrapper5?: Flex__<"div">;
  wrapper?: Flex__<"div">;
  textInput5?: Flex__<typeof TextInput>;
  wrapper2?: Flex__<"div">;
  progressBar?: Flex__<"div">;
  signedByBaseProgressBarSteppedMediumLabelNone?: Flex__<"div">;
  progress?: Flex__<"div">;
  inProgress?: Flex__<"div">;
  base?: Flex__<"div">;
  base2?: Flex__<"div">;
  base3?: Flex__<"div">;
  base4?: Flex__<"div">;
  base5?: Flex__<"div">;
  base6?: Flex__<"div">;
  text?: Flex__<"div">;
  textInput6?: Flex__<typeof TextInput>;
  checkboxWrapper?: Flex__<"div">;
  checkBox?: Flex__<typeof CheckBox>;
  buttonWrapper?: Flex__<"div">;
  button?: Flex__<"div">;
  dividerWrapper?: Flex__<"div">;
  text4?: Flex__<"div">;
  buttonWrapper2?: Flex__<"div">;
  linkWrapper?: Flex__<"div">;
  text5?: Flex__<"div">;
  textLink2?: Flex__<typeof TextLink>;
};

export interface DefaultInscriptionProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicInscription__RenderFunc(props: {
  variants: PlasmicInscription__VariantsArgs;
  args: PlasmicInscription__ArgsType;
  overrides: PlasmicInscription__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshm8Nko4B5BDd()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicInscription.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicInscription.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicInscription.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"inscription"}
          data-plasmic-override={overrides.inscription}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens,
            sty.inscription
          )}
        >
          <div
            data-plasmic-name={"signUp"}
            data-plasmic-override={overrides.signUp}
            className={classNames(projectcss.all, sty.signUp)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"imageWrapper"}
              data-plasmic-override={overrides.imageWrapper}
              hasGap={true}
              className={classNames(projectcss.all, sty.imageWrapper)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"logoWrapper"}
                data-plasmic-override={overrides.logoWrapper}
                hasGap={true}
                className={classNames(projectcss.all, sty.logoWrapper)}
              >
                <PictogramIcon
                  className={classNames(projectcss.all, sty.svg___5GksB)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"baseline"}
                  data-plasmic-override={overrides.baseline}
                  className={classNames(projectcss.all, sty.baseline)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame"}
                    data-plasmic-override={overrides.frame}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__icH4P
                      )}
                    >
                      {"JOB"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame2"}
                    data-plasmic-override={overrides.frame2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gGygv
                      )}
                    >
                      {"AROUND"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame3"}
                    data-plasmic-override={overrides.frame3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sFPa0
                      )}
                    >
                      {"ME"}
                    </div>
                  </Stack__>
                </div>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"formWrapper"}
              data-plasmic-override={overrides.formWrapper}
              hasGap={true}
              className={classNames(projectcss.all, sty.formWrapper)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"form"}
                data-plasmic-override={overrides.form}
                hasGap={true}
                className={classNames(projectcss.all, sty.form)}
              >
                <div
                  data-plasmic-name={"title"}
                  data-plasmic-override={overrides.title}
                  className={classNames(projectcss.all, sty.title)}
                >
                  <div
                    data-plasmic-name={"heading"}
                    data-plasmic-override={overrides.heading}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.heading
                    )}
                  >
                    {"Inscription"}
                  </div>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"inputWrapper"}
                  data-plasmic-override={overrides.inputWrapper}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.inputWrapper)}
                >
                  <TextInput
                    data-plasmic-name={"textInput"}
                    data-plasmic-override={overrides.textInput}
                    className={classNames("__wab_instance", sty.textInput)}
                    prefixedText={``}
                    type={"default"}
                  />

                  <TextInput
                    data-plasmic-name={"textInput2"}
                    data-plasmic-override={overrides.textInput2}
                    className={classNames("__wab_instance", sty.textInput2)}
                    prefixedText={``}
                    type={"default"}
                  />
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"inputWrapper2"}
                  data-plasmic-override={overrides.inputWrapper2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.inputWrapper2)}
                >
                  <TextInput
                    data-plasmic-name={"textInput3"}
                    data-plasmic-override={overrides.textInput3}
                    className={classNames("__wab_instance", sty.textInput3)}
                    prefixedText={``}
                    type={"default"}
                  />
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"inputWrapper3"}
                  data-plasmic-override={overrides.inputWrapper3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.inputWrapper3)}
                >
                  <div
                    data-plasmic-name={"label"}
                    data-plasmic-override={overrides.label}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.label
                    )}
                  >
                    {"T\u00e9l\u00e9phone*"}
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"inputWrapper4"}
                    data-plasmic-override={overrides.inputWrapper4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.inputWrapper4)}
                  >
                    <PhoneSelector
                      data-plasmic-name={"phoneSelector"}
                      data-plasmic-override={overrides.phoneSelector}
                      className={classNames(
                        "__wab_instance",
                        sty.phoneSelector
                      )}
                    />

                    <TextInput
                      data-plasmic-name={"textInput4"}
                      data-plasmic-override={overrides.textInput4}
                      className={classNames("__wab_instance", sty.textInput4)}
                      prefixedText={``}
                      type={"default"}
                    />
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"inputWrapper5"}
                  data-plasmic-override={overrides.inputWrapper5}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.inputWrapper5)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"wrapper"}
                    data-plasmic-override={overrides.wrapper}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.wrapper)}
                  >
                    <TextInput
                      data-plasmic-name={"textInput5"}
                      data-plasmic-override={overrides.textInput5}
                      className={classNames("__wab_instance", sty.textInput5)}
                      prefixedText={``}
                      type={"default"}
                    />

                    <Stack__
                      as={"div"}
                      data-plasmic-name={"wrapper2"}
                      data-plasmic-override={overrides.wrapper2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.wrapper2)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"progressBar"}
                        data-plasmic-override={overrides.progressBar}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.progressBar)}
                      >
                        {false ? (
                          <div
                            data-plasmic-name={
                              "signedByBaseProgressBarSteppedMediumLabelNone"
                            }
                            data-plasmic-override={
                              overrides.signedByBaseProgressBarSteppedMediumLabelNone
                            }
                            className={classNames(
                              projectcss.all,
                              sty.signedByBaseProgressBarSteppedMediumLabelNone
                            )}
                          />
                        ) : null}
                        {false ? (
                          <div
                            data-plasmic-name={"progress"}
                            data-plasmic-override={overrides.progress}
                            className={classNames(projectcss.all, sty.progress)}
                          />
                        ) : null}
                        {false ? (
                          <div
                            data-plasmic-name={"inProgress"}
                            data-plasmic-override={overrides.inProgress}
                            className={classNames(
                              projectcss.all,
                              sty.inProgress
                            )}
                          />
                        ) : null}
                        <div
                          data-plasmic-name={"base"}
                          data-plasmic-override={overrides.base}
                          className={classNames(projectcss.all, sty.base)}
                        />

                        <div
                          data-plasmic-name={"base2"}
                          data-plasmic-override={overrides.base2}
                          className={classNames(projectcss.all, sty.base2)}
                        />

                        <div
                          data-plasmic-name={"base3"}
                          data-plasmic-override={overrides.base3}
                          className={classNames(projectcss.all, sty.base3)}
                        />

                        <div
                          data-plasmic-name={"base4"}
                          data-plasmic-override={overrides.base4}
                          className={classNames(projectcss.all, sty.base4)}
                        />

                        {false ? (
                          <div
                            data-plasmic-name={"base5"}
                            data-plasmic-override={overrides.base5}
                            className={classNames(projectcss.all, sty.base5)}
                          />
                        ) : null}
                        {false ? (
                          <div
                            data-plasmic-name={"base6"}
                            data-plasmic-override={overrides.base6}
                            className={classNames(projectcss.all, sty.base6)}
                          />
                        ) : null}
                      </Stack__>
                      <div
                        data-plasmic-name={"text"}
                        data-plasmic-override={overrides.text}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text
                        )}
                      >
                        {
                          "Utilisez 8 caract\u00e8res ou plus en m\u00e9langeant lettres, chiffres et symboles."
                        }
                      </div>
                    </Stack__>
                  </Stack__>
                  <TextInput
                    data-plasmic-name={"textInput6"}
                    data-plasmic-override={overrides.textInput6}
                    className={classNames("__wab_instance", sty.textInput6)}
                    prefixedText={``}
                    type={"default"}
                  />
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"checkboxWrapper"}
                  data-plasmic-override={overrides.checkboxWrapper}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.checkboxWrapper)}
                >
                  <CheckBox
                    data-plasmic-name={"checkBox"}
                    data-plasmic-override={overrides.checkBox}
                    className={classNames("__wab_instance", sty.checkBox)}
                    type={"Checkbox"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oJoXk
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"J'accepte la"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {" politique de confidentialit\u00e9"}
                      </span>
                    </React.Fragment>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"buttonWrapper"}
                  data-plasmic-override={overrides.buttonWrapper}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.buttonWrapper)}
                >
                  <div
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(projectcss.all, sty.button)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__yv9Ep
                      )}
                      icon={"none"}
                      iconImage={
                        "/plasmic/jam_v_jean_loader/images/iconSocialsGoogle.svg"
                      }
                      label={"INSCRIPTION"}
                    />
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"dividerWrapper"}
                    data-plasmic-override={overrides.dividerWrapper}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.dividerWrapper)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kgw2F)}
                    >
                      <DividerLineIcon
                        className={classNames(projectcss.all, sty.svg__u9Sek)}
                        role={"img"}
                      />
                    </div>
                    <div
                      data-plasmic-name={"text4"}
                      data-plasmic-override={overrides.text4}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text4
                      )}
                    >
                      {"OU"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ruAkS)}
                    >
                      <DividerLineIcon
                        className={classNames(projectcss.all, sty.svg__lMy9F)}
                        role={"img"}
                      />
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"buttonWrapper2"}
                  data-plasmic-override={overrides.buttonWrapper2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.buttonWrapper2)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__z1FDc)}
                    icon={"start"}
                    iconImage={
                      "/plasmic/jam_v_jean_loader/images/iconSocialsGoogle.svg"
                    }
                    label={"GOOGLE"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__b2RNl)}
                    icon={"start"}
                    iconImage={
                      "/plasmic/jam_v_jean_loader/images/iconSocialsApple.svg"
                    }
                    label={"APPLE"}
                  />
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"linkWrapper"}
                  data-plasmic-override={overrides.linkWrapper}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.linkWrapper)}
                >
                  <div
                    data-plasmic-name={"text5"}
                    data-plasmic-override={overrides.text5}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text5
                    )}
                  >
                    {"D\u00e9j\u00e0 inscrit(e) ?"}
                  </div>
                  <TextLink
                    data-plasmic-name={"textLink2"}
                    data-plasmic-override={overrides.textLink2}
                    className={classNames("__wab_instance", sty.textLink2)}
                    icon={"None"}
                    label={"connexion"}
                    redirect={""}
                    size={"Small"}
                    uppercase={true}
                  />
                </Stack__>
              </Stack__>
            </Stack__>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  inscription: [
    "inscription",
    "signUp",
    "imageWrapper",
    "logoWrapper",
    "baseline",
    "frame",
    "frame2",
    "frame3",
    "formWrapper",
    "form",
    "title",
    "heading",
    "inputWrapper",
    "textInput",
    "textInput2",
    "inputWrapper2",
    "textInput3",
    "inputWrapper3",
    "label",
    "inputWrapper4",
    "phoneSelector",
    "textInput4",
    "inputWrapper5",
    "wrapper",
    "textInput5",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "textInput6",
    "checkboxWrapper",
    "checkBox",
    "buttonWrapper",
    "button",
    "dividerWrapper",
    "text4",
    "buttonWrapper2",
    "linkWrapper",
    "text5",
    "textLink2"
  ],
  signUp: [
    "signUp",
    "imageWrapper",
    "logoWrapper",
    "baseline",
    "frame",
    "frame2",
    "frame3",
    "formWrapper",
    "form",
    "title",
    "heading",
    "inputWrapper",
    "textInput",
    "textInput2",
    "inputWrapper2",
    "textInput3",
    "inputWrapper3",
    "label",
    "inputWrapper4",
    "phoneSelector",
    "textInput4",
    "inputWrapper5",
    "wrapper",
    "textInput5",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "textInput6",
    "checkboxWrapper",
    "checkBox",
    "buttonWrapper",
    "button",
    "dividerWrapper",
    "text4",
    "buttonWrapper2",
    "linkWrapper",
    "text5",
    "textLink2"
  ],
  imageWrapper: [
    "imageWrapper",
    "logoWrapper",
    "baseline",
    "frame",
    "frame2",
    "frame3"
  ],
  logoWrapper: ["logoWrapper", "baseline", "frame", "frame2", "frame3"],
  baseline: ["baseline", "frame", "frame2", "frame3"],
  frame: ["frame"],
  frame2: ["frame2"],
  frame3: ["frame3"],
  formWrapper: [
    "formWrapper",
    "form",
    "title",
    "heading",
    "inputWrapper",
    "textInput",
    "textInput2",
    "inputWrapper2",
    "textInput3",
    "inputWrapper3",
    "label",
    "inputWrapper4",
    "phoneSelector",
    "textInput4",
    "inputWrapper5",
    "wrapper",
    "textInput5",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "textInput6",
    "checkboxWrapper",
    "checkBox",
    "buttonWrapper",
    "button",
    "dividerWrapper",
    "text4",
    "buttonWrapper2",
    "linkWrapper",
    "text5",
    "textLink2"
  ],
  form: [
    "form",
    "title",
    "heading",
    "inputWrapper",
    "textInput",
    "textInput2",
    "inputWrapper2",
    "textInput3",
    "inputWrapper3",
    "label",
    "inputWrapper4",
    "phoneSelector",
    "textInput4",
    "inputWrapper5",
    "wrapper",
    "textInput5",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "textInput6",
    "checkboxWrapper",
    "checkBox",
    "buttonWrapper",
    "button",
    "dividerWrapper",
    "text4",
    "buttonWrapper2",
    "linkWrapper",
    "text5",
    "textLink2"
  ],
  title: ["title", "heading"],
  heading: ["heading"],
  inputWrapper: ["inputWrapper", "textInput", "textInput2"],
  textInput: ["textInput"],
  textInput2: ["textInput2"],
  inputWrapper2: ["inputWrapper2", "textInput3"],
  textInput3: ["textInput3"],
  inputWrapper3: [
    "inputWrapper3",
    "label",
    "inputWrapper4",
    "phoneSelector",
    "textInput4"
  ],
  label: ["label"],
  inputWrapper4: ["inputWrapper4", "phoneSelector", "textInput4"],
  phoneSelector: ["phoneSelector"],
  textInput4: ["textInput4"],
  inputWrapper5: [
    "inputWrapper5",
    "wrapper",
    "textInput5",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "textInput6"
  ],
  wrapper: [
    "wrapper",
    "textInput5",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text"
  ],
  textInput5: ["textInput5"],
  wrapper2: [
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text"
  ],
  progressBar: [
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6"
  ],
  signedByBaseProgressBarSteppedMediumLabelNone: [
    "signedByBaseProgressBarSteppedMediumLabelNone"
  ],
  progress: ["progress"],
  inProgress: ["inProgress"],
  base: ["base"],
  base2: ["base2"],
  base3: ["base3"],
  base4: ["base4"],
  base5: ["base5"],
  base6: ["base6"],
  text: ["text"],
  textInput6: ["textInput6"],
  checkboxWrapper: ["checkboxWrapper", "checkBox"],
  checkBox: ["checkBox"],
  buttonWrapper: ["buttonWrapper", "button", "dividerWrapper", "text4"],
  button: ["button"],
  dividerWrapper: ["dividerWrapper", "text4"],
  text4: ["text4"],
  buttonWrapper2: ["buttonWrapper2"],
  linkWrapper: ["linkWrapper", "text5", "textLink2"],
  text5: ["text5"],
  textLink2: ["textLink2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  inscription: "div";
  signUp: "div";
  imageWrapper: "div";
  logoWrapper: "div";
  baseline: "div";
  frame: "div";
  frame2: "div";
  frame3: "div";
  formWrapper: "div";
  form: "div";
  title: "div";
  heading: "div";
  inputWrapper: "div";
  textInput: typeof TextInput;
  textInput2: typeof TextInput;
  inputWrapper2: "div";
  textInput3: typeof TextInput;
  inputWrapper3: "div";
  label: "div";
  inputWrapper4: "div";
  phoneSelector: typeof PhoneSelector;
  textInput4: typeof TextInput;
  inputWrapper5: "div";
  wrapper: "div";
  textInput5: typeof TextInput;
  wrapper2: "div";
  progressBar: "div";
  signedByBaseProgressBarSteppedMediumLabelNone: "div";
  progress: "div";
  inProgress: "div";
  base: "div";
  base2: "div";
  base3: "div";
  base4: "div";
  base5: "div";
  base6: "div";
  text: "div";
  textInput6: typeof TextInput;
  checkboxWrapper: "div";
  checkBox: typeof CheckBox;
  buttonWrapper: "div";
  button: "div";
  dividerWrapper: "div";
  text4: "div";
  buttonWrapper2: "div";
  linkWrapper: "div";
  text5: "div";
  textLink2: typeof TextLink;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicInscription__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicInscription__VariantsArgs;
    args?: PlasmicInscription__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicInscription__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicInscription__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicInscription__ArgProps,
          internalVariantPropNames: PlasmicInscription__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicInscription__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "inscription") {
    func.displayName = "PlasmicInscription";
  } else {
    func.displayName = `PlasmicInscription.${nodeName}`;
  }
  return func;
}

export const PlasmicInscription = Object.assign(
  // Top-level PlasmicInscription renders the root element
  makeNodeComponent("inscription"),
  {
    // Helper components rendering sub-elements
    signUp: makeNodeComponent("signUp"),
    imageWrapper: makeNodeComponent("imageWrapper"),
    logoWrapper: makeNodeComponent("logoWrapper"),
    baseline: makeNodeComponent("baseline"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    frame3: makeNodeComponent("frame3"),
    formWrapper: makeNodeComponent("formWrapper"),
    form: makeNodeComponent("form"),
    title: makeNodeComponent("title"),
    heading: makeNodeComponent("heading"),
    inputWrapper: makeNodeComponent("inputWrapper"),
    textInput: makeNodeComponent("textInput"),
    textInput2: makeNodeComponent("textInput2"),
    inputWrapper2: makeNodeComponent("inputWrapper2"),
    textInput3: makeNodeComponent("textInput3"),
    inputWrapper3: makeNodeComponent("inputWrapper3"),
    label: makeNodeComponent("label"),
    inputWrapper4: makeNodeComponent("inputWrapper4"),
    phoneSelector: makeNodeComponent("phoneSelector"),
    textInput4: makeNodeComponent("textInput4"),
    inputWrapper5: makeNodeComponent("inputWrapper5"),
    wrapper: makeNodeComponent("wrapper"),
    textInput5: makeNodeComponent("textInput5"),
    wrapper2: makeNodeComponent("wrapper2"),
    progressBar: makeNodeComponent("progressBar"),
    signedByBaseProgressBarSteppedMediumLabelNone: makeNodeComponent(
      "signedByBaseProgressBarSteppedMediumLabelNone"
    ),
    progress: makeNodeComponent("progress"),
    inProgress: makeNodeComponent("inProgress"),
    base: makeNodeComponent("base"),
    base2: makeNodeComponent("base2"),
    base3: makeNodeComponent("base3"),
    base4: makeNodeComponent("base4"),
    base5: makeNodeComponent("base5"),
    base6: makeNodeComponent("base6"),
    text: makeNodeComponent("text"),
    textInput6: makeNodeComponent("textInput6"),
    checkboxWrapper: makeNodeComponent("checkboxWrapper"),
    checkBox: makeNodeComponent("checkBox"),
    buttonWrapper: makeNodeComponent("buttonWrapper"),
    button: makeNodeComponent("button"),
    dividerWrapper: makeNodeComponent("dividerWrapper"),
    text4: makeNodeComponent("text4"),
    buttonWrapper2: makeNodeComponent("buttonWrapper2"),
    linkWrapper: makeNodeComponent("linkWrapper"),
    text5: makeNodeComponent("text5"),
    textLink2: makeNodeComponent("textLink2"),

    // Metadata about props expected for PlasmicInscription
    internalVariantProps: PlasmicInscription__VariantProps,
    internalArgProps: PlasmicInscription__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Inscription",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicInscription;
/* prettier-ignore-end */
